version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/innowise_db
      - SPRING_DATASOURCE_USERNAME=temp
      - SPRING_DATASOURCE_PASSWORD=temp
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: inno-db
    restart: always
    environment:
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp
      - POSTGRES_DB=innowise_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: